version: "3.9"
services:
  furniture-shop:
    image: docker.io/raseefk/furniture-shop-management-oracle:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      ORACLE_HOST: host.docker.internal
      ORACLE_PORT: 1521
      ORACLE_SERVICE: FREEPDB1
      ORACLE_USERNAME: furniture
      ORACLE_PASSWORD: admin123
